services:

  # --- PATIENT SERVICE DB ---
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PATIENT_SERVICE_DB_PORT_EXTERNAL}:5432"
    volumes:
      - patient_db_data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- AUTH SERVICE DB ---
  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${AUTH_SERVICE_DB_PORT_EXTERNAL}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- PATIENT SERVICE ---
  patient-service:
    build:
      context: ./patient-service
    image: patient-service:latest
    container_name: patient-service
    depends_on:
      patient-service-db:
        condition: service_healthy
      billing-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:${DB_PORT_INTERNAL}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_DDL_AUTO}
      - SPRING_SQL_INIT_MODE=${SQL_INIT_MODE}
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=${BILLING_SERVICE_GRPC_PORT}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - app-network

  # --- AUTH SERVICE ---
  auth-service:
    build:
      context: ./auth-service
    image: auth-service:latest
    container_name: auth-service
    depends_on:
      auth-service-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:${DB_PORT_INTERNAL}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_DDL_AUTO}
      - SPRING_SQL_INIT_MODE=${SQL_INIT_MODE}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  # --- BILLING SERVICE ---
  billing-service:
    build:
      context: ./billing-service
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "${BILLING_SERVICE_HTTP_PORT}:${BILLING_SERVICE_HTTP_PORT}"
      - "${BILLING_SERVICE_GRPC_PORT}:9001"
    networks:
      - app-network

  # --- Kafka ---
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "${KAFKA_PORT_EXTERNAL}:9092"
      - "${KAFKA_PORT_DEVELOPMENT}:${KAFKA_PORT_DEVELOPMENT}"
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:${KAFKA_PORT_DEVELOPMENT}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:${KAFKA_PORT_DEVELOPMENT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    networks:
      - app-network

  # --- Analytics Service ---
  analytics-service:
    build:
      context: ./analytics-service
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "${ANALYTICS_SERVICE_HTTP_PORT}:${ANALYTICS_SERVICE_HTTP_PORT}"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - app-network

  # --- Api Gateway ---
  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_HTTP_PORT}:${API_GATEWAY_HTTP_PORT}"
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
    networks:
      - app-network


# --- SHARED RESOURCES ---
networks:
  app-network: # One unified network for all services

volumes:
  patient_db_data:
  auth_db_data: